### PR TITLE
feat!: support for Kubeconfig merging

### LINKED ISSUE #16: Automatically export KUBECONFIG enviroment
Describe the feature

Hi all.
I would like a lot a feature that automatically export the KUBECONFIG for the user after complete the login process

What would the new user story look like?

Once a user has completed the login process, kubetcl-login automatically export the KUBECONFIG for the user, instead of ask to the user to export with the command "export KUBECONFIG=oidc.kubeconfig"

### PR DESCRIPTION
**Pull request by prometherion**
Closes #16.

Flag `kubeconfig-path` is no more mandatory and in case of empty string, using the environment variable `KUBECONFIG` or the default location (`$HOME/.kube/config`)

### CODE REVIEW

**Comment by prometherion** [comment]
@bsctl may I ask you a test for this?

**Review by bsctl — COMMENTED** [review]
@prometherion Thanks, it looks great to me.

Just a couple of points:

1. the server is named always as `kubernetes` in the merged `kubeconfig` file. If there is another server in the current `kubeconfig` file already called `kubernetes`, it will be overwritten. What about to take the name from the `--k8s-api-server` option value? Or better, from the `kubeconfig cluster-info` API? Anyway this can be tracked with another issue and we do not need to solve it in this PR.

2. Please update the README describing the new behaviour.

**Comment by prometherion** [comment]
> the server is named always as kubernetes in the merged kubeconfig file. If there is another server in the current kubeconfig file already called kubernetes, it will be overwritten. What about to take the name from the --k8s-api-server option value? Or better, from the kubeconfig cluster-info API? Anyway this can be tracked with another issue and we do not need to solve it in this PR.

Let's track in another issue.

**Review by bsctl — APPROVED** [review]
lgtm!

**Pull request merged**
